### ISSUE TITLE
节点和关系的数据格式

### ISSUE THREAD

**Issue by xumeng123** [Jeff-Bee/knowledgeGraph#1]
请问节点和关系的数据格式是啥样？

**Comment by Jeff-Bee** [comment]
目前用的数据结构类似树结构,使用children做为子节点,在echarts中用seriesLinks  这个数组存储,value和target做关联关系,可以看一下echarts.vue组件展开方法逻辑

**Comment by Jeff-Bee** [comment]
目前用的数据结构类似树结构,使用children做为子节点,在echarts中用seriesLinks 这个数组存储,value和target做关联关系,可以看一下echarts.vue组件展开方法逻辑
